spring:
  data:
    mongodb:
      host: ${DB_HOST}
      username: ${DB_ROOT_USERNAME}
      password: ${DB_ROOT_PASSWORD}
      database: ${DB_NAME}
      port: ${DB_PORT:27017}
      authentication-database: admin
fillist:
  allow-origin: ${ALLOW_ORIGIN}
  oauth2:
    jwt-secret: ${JWT_SECRET}
    client:
      registration:
        spotify:
          client-id: ${SPOTIFY_CLIENT_ID}
          secret: ${SPOTIFY_CLIENT_SECRET}
          redirect-uri: http://localhost:4200/callback
          spotify-idp-uri: https://accounts.spotify.com
          scope: user-read-private,user-read-email,user-library-read,user-library-modify,user-read-playback-state,user-modify-playback-state,user-read-currently-playing,user-read-recently-played
