name: Frontend CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  ci:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: 'yarn'
          cache-dependency-path: 'frontend/yarn.lock'
      - name: Install dependencies
        run: yarn install --frozen-lockfile
      - name: Test app
        run: yarn run test:prod
      - name: Build app
        run: yarn run build
      - name: Run ESLint
        run: npx eslint .
          --config .eslintrc.json
          --ext .js,.jsx,.ts,.tsx
          --fix
          --format @microsoft/eslint-formatter-sarif
          --output-file eslint-results.sarif
        continue-on-error: true
      - name: Upload analysis results to GitHub
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: frontend/eslint-results.sarif
          wait-for-processing: true
      - name: Remove result
        run: rm eslint-results.sarif
      - name: Push and commit eslint fixes
          - uses: actions/checkout@v3
          - run: |
              git config --local user.email "noreply@akai.org"
              git config --local user.name "GitHub Action"
              git add .
              git commit -m "[CI] Automatic Eslint Fix"
              git push
