name: Frontend CD

on:
  push:
    branches: [ "release" ]

jobs:
  cd:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend
    permissions:
      contents: write
      security-events: write
      actions: write
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js 20.x
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: 'yarn'
          cache-dependency-path: 'frontend/yarn.lock'
      - name: Install dependencies
        run: yarn install --frozen-lockfile
      - name: Test app
        run: yarn run test:prod
      - name: Deploy app
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: yarn run deploy

